export const BUSINESS = {
  name: "Solange's Hair Braiding LLC",
  shortName: "Solange's",
  tagline: "Braids • Beauty • Confidence",
  phone1: "443.320.1312",
  phone2: "202.445.8152",
  phone1Raw: "4433201312",
  phone2Raw: "2024458152",
  address: "550 Crain Highway N, Glen Burnie, MD 21061",
  addressLine2: "Inside Crain Plaza",
  email: "solangesbraidingsalon@gmail.com",
  instagram: "@solangehairbraiding",
  instagramUrl: "https://www.instagram.com/solangehairbraiding",
  facebook: "Solange's Hair Braiding",
  tiktok: "@solangehairbraiding",
  whatsapp: "4433201312",
  hours: {
    weekdays: "Mon – Sat: 8:00 AM – 7:00 PM",
    sunday: "Sunday: Closed",
  },
  yearsExperience: 15,
  happyClients: "5,000+",
  totalStyles: "20,000+",
  rating: 5,
  ratingCount: "132+",
  deposit: 30,
  newClientDiscount: 15,
  studentDiscount: 10,
  referralDiscount: 20,
} as const;

export const SERVICES = [
  {
    slug: "knotless-braids",
    name: "Knotless Braids",
    category: "braids",
    description: "Lightweight, natural looking braids with less tension on the scalp.",
    startingPrice: 180,
    duration: "4-6 hours",
    featured: true,
    icon: "scissors",
  },
  {
    slug: "box-braids",
    name: "Box Braids",
    category: "braids",
    description: "Classic, stylish & versatile. Comes in different sizes and lengths.",
    startingPrice: 150,
    duration: "4-7 hours",
    featured: true,
    icon: "scissors",
  },
  {
    slug: "boho-braids",
    name: "Boho Braids",
    category: "braids",
    description: "Bohemian, curly & beautiful. Perfect for a soft, natural look.",
    startingPrice: 200,
    duration: "5-8 hours",
    featured: true,
    icon: "flower",
  },
  {
    slug: "passion-twist",
    name: "Passion Twist",
    category: "twists",
    description: "Lightweight, natural looking twists with a passionate touch.",
    startingPrice: 190,
    duration: "4-6 hours",
    featured: true,
    icon: "sparkles",
  },
  {
    slug: "feed-in-braids",
    name: "Feed-In Braids",
    category: "cornrows",
    description: "Neat, clean & stylish braids close to the scalp.",
    startingPrice: 60,
    duration: "2-3 hours",
    featured: true,
    icon: "crown",
  },
  {
    slug: "stitch-braids",
    name: "Stitch Braids",
    category: "cornrows",
    description: "Clean stitch lines for a sharp, defined look.",
    startingPrice: 80,
    duration: "2-4 hours",
    featured: false,
    icon: "crown",
  },
  {
    slug: "senegalese-twist",
    name: "Senegalese Twist",
    category: "twists",
    description: "Sleek, twisted & lightweight for a natural look.",
    startingPrice: 180,
    duration: "4-7 hours",
    featured: true,
    icon: "sparkles",
  },
  {
    slug: "kids-braids",
    name: "Kids Braids",
    category: "kids",
    description: "Cute, creative & kid-friendly styles they'll love.",
    startingPrice: 45,
    duration: "1-3 hours",
    featured: true,
    icon: "users",
  },
  {
    slug: "starter-locs",
    name: "Starter Locs",
    category: "locs",
    description: "Begin your loc journey with expert guidance.",
    startingPrice: 100,
    duration: "2-4 hours",
    featured: false,
    icon: "star",
  },
  {
    slug: "loc-retwist",
    name: "Loc Retwist",
    category: "locs",
    description: "Keep your locs neat and healthy with regular retwists.",
    startingPrice: 80,
    duration: "2-3 hours",
    featured: false,
    icon: "star",
  },
  {
    slug: "butterfly-locs",
    name: "Butterfly Locs",
    category: "locs",
    description: "Soft, flowy locs with a bohemian texture. Light and stunning.",
    startingPrice: 200,
    duration: "5-8 hours",
    featured: true,
    icon: "sparkles",
  },
  {
    slug: "frontal-install",
    name: "Frontal Install",
    category: "weaves",
    description: "Flawless frontal installation for a natural hairline.",
    startingPrice: 150,
    duration: "3-4 hours",
    featured: false,
    icon: "crown",
  },
  {
    slug: "fulani-braids",
    name: "Fulani Braids",
    category: "braids",
    description: "Traditional African-inspired braids with modern elegance and style.",
    startingPrice: 180,
    duration: "4-6 hours",
    featured: false,
    icon: "scissors",
  },
] as const;

export const ADDONS = [
  { name: "Hair Wash", price: 20 },
  { name: "Deep Conditioning", price: 20 },
  { name: "Hair Included (X-Pression)", price: "30+" },
  { name: "Boho/Curly Hair", price: "30+" },
  { name: "Beads / Accessories", price: "10+" },
  { name: "Take Down", price: "25+" },
  { name: "Edge Styling", price: "10+" },
];

export const LENGTH_GUIDE = [
  { length: "Shoulder Length", label: "Shoulder", add: 0, note: "Base Price" },
  { length: "Mid Back", label: "Mid Back", add: 20 },
  { length: "Lower Back", label: "Lower Back", add: 40 },
  { length: "Waist", label: "Waist", add: 60 },
  { length: "Butt", label: "Butt", add: 80 },
  { length: "Knee Length", label: "Knee", add: 100 },
];

export const TEAM = [
  {
    name: "Solange",
    title: "Founder & Lead Stylist",
    description: "With over 15 years of experience, Solange specializes in all braiding techniques and is passionate about helping you look and feel your best.",
  },
  {
    name: "Jessica",
    title: "Senior Stylist",
    description: "Expert in knotless braids, boho styles, and twists. Jessica loves creating soft, natural looks for every client.",
  },
  {
    name: "Tiffany",
    title: "Locs & Braids Specialist",
    description: "Specializes in loc maintenance, loc styles, and intricate braids. Detail-oriented and dedicated to perfection.",
  },
  {
    name: "Monique",
    title: "Junior Stylist",
    description: "Passionate, creative, and always learning. Monique brings energy and care to every style.",
  },
];

export const REVIEWS = [
  {
    name: "Tiffany R.",
    rating: 5,
    text: "Solange is amazing! My braids are always neat, lightweight and last so long. The best braiding salon in Glen Burnie!",
    date: "2 weeks ago",
  },
  {
    name: "Monique L.",
    rating: 5,
    text: "Professional, clean, and such a welcoming environment. I wouldn't go anywhere else!",
    date: "1 month ago",
  },
  {
    name: "Danielle P.",
    rating: 5,
    text: "My daughter loves coming here for her box braids. Kid-friendly and always beautiful results!",
    date: "3 weeks ago",
  },
];

export const FAQS = {
  general: [
    { q: "What types of hair do you work with?", a: "We work with all hair types including natural, relaxed, and transitioning hair. We specialize in protective styles for all textures." },
    { q: "How long does my appointment take?", a: "Appointment times vary by style. Knotless braids take 4-6 hours, box braids 4-7 hours, cornrows 2-3 hours, and kids styles 1-3 hours." },
    { q: "How much do your braids cost?", a: "Our prices start at $45 for kids styles and go up depending on the style, length, and complexity. Visit our pricing page for full details." },
    { q: "Do you offer consultations?", a: "Yes! We offer free consultations. You can call, text, or WhatsApp us to discuss your desired style before booking." },
    { q: "Do you provide hair for the styles?", a: "Yes, we can provide hair for most styles for an additional fee. You're also welcome to bring your own hair." },
  ],
  booking: [
    { q: "How do I book an appointment?", a: "You can book online 24/7 through our booking page, call us at 443.320.1312, or walk in (appointments recommended)." },
    { q: "Do you accept walk-ins?", a: "Yes, walk-ins are welcome! However, we highly recommend booking in advance to secure your preferred time slot, especially on weekends." },
    { q: "Do I need to pay a deposit?", a: "Yes, a $30 non-refundable deposit is required to secure your appointment. This deposit is applied toward your total service cost." },
    { q: "How do I reschedule or cancel?", a: "Please give us at least 24 hours notice to reschedule or cancel. Late cancellations may result in forfeiture of your deposit." },
    { q: "How early should I arrive for my appointment?", a: "Please arrive 10-15 minutes early. Late arrivals may result in rescheduling." },
  ],
  hairCare: [
    { q: "How do I care for my braids?", a: "Moisturize your scalp daily with a light oil or spray, wrap your hair at night with a satin scarf or bonnet, and avoid excessive pulling or tension." },
    { q: "How long will my braids last?", a: "With proper care, braids typically last 4-8 weeks. Knotless and box braids can last up to 8 weeks." },
    { q: "Can I wash my hair with braids?", a: "Yes! We recommend washing every 2-3 weeks using a diluted shampoo. Focus on the scalp and let braids air dry." },
    { q: "What products do you recommend?", a: "We recommend lightweight oils (jojoba, argan), leave-in conditioners, and edge control. We can recommend specific products during your appointment." },
    { q: "Do you do take-downs?", a: "Yes, we offer take-down services. Please book this as a separate service or add-on when scheduling." },
  ],
};

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "Services", href: "/services", hasDropdown: true },
  { label: "Gallery", href: "/gallery" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];
